// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvaloniaReactorUI.ScaffoldApp
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Reflection;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TypeSourceGenerator : TypeSourceGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// ------------------------------------------------------------------------------" +
                    "\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//     Avaloni" +
                    "aReactorUI.ScaffoldApp Version: ");
            
            #line 10 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Assembly.GetExecutingAssembly().GetName().Version));
            
            #line default
            #line hidden
            this.Write(@"
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Windows.Input;
using System.Collections;

using Avalonia;
using Avalonia.Animation;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Interactivity;
using Avalonia.Input;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.Templates;
using Avalonia.Platform;
using Avalonia.Controls.Selection;
using Avalonia.Input.TextInput;

using AvaloniaReactorUI.Internals;

namespace AvaloniaReactorUI
{
    public partial interface IRx");
            
            #line 39 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" : I");
            
            #line 39 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseTypeName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n    ");
            
            #line 41 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var property in Properties) { 
            
            #line default
            #line hidden
            this.Write("        PropertyValue<");
            
            #line 42 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 42 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n    ");
            
            #line 43 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 45 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("        Action ");
            
            #line 46 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("Action { get; set; }\r\n        Action<");
            
            #line 47 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.EventHandlerType.GetGenericArguments()[0].Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 47 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs { get; set; }\r\n    ");
            
            #line 48 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n    \r\n    public partial class Rx");
            
            #line 51 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("<T> : ");
            
            #line 51 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseTypeName));
            
            #line default
            #line hidden
            this.Write("<T>, IRx");
            
            #line 51 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" where T : ");
            
            #line 51 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(", new()\r\n    {\r\n        public Rx");
            
            #line 53 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("()\r\n        { \r\n        \r\n        }\r\n\r\n        public Rx");
            
            #line 58 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("(Action<T> componentRefAction)\r\n            : base(componentRefAction)\r\n        {" +
                    "\r\n\r\n        }\r\n\r\n        ");
            
            #line 64 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var property in Properties) { 
            
            #line default
            #line hidden
            this.Write("        PropertyValue<");
            
            #line 65 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write("> IRx");
            
            #line 65 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 65 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n        ");
            
            #line 66 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 68 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("        Action IRx");
            
            #line 69 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 69 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("Action { get; set; }\r\n        Action<");
            
            #line 70 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.EventHandlerType.GetGenericArguments()[0].Name));
            
            #line default
            #line hidden
            this.Write("> IRx");
            
            #line 70 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 70 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs { get; set; }\r\n        ");
            
            #line 71 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        protected override void OnUpdate()\r\n        {\r\n            OnBeginUpdat" +
                    "e();\r\n\r\n            var thisAsIRx");
            
            #line 77 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" = (IRx");
            
            #line 77 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(")this;\r\n            ");
            
            #line 78 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var property in Properties) { 
            
            #line default
            #line hidden
            this.Write("            NativeControl.Set(");
            
            #line 79 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 79 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("Property, thisAsIRx");
            
            #line 79 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 79 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n            ");
            
            #line 80 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            base.OnUpdate();\r\n\r\n            OnEndUpdate();\r\n        }\r\n\r\n      " +
                    "  partial void OnBeginUpdate();\r\n        partial void OnEndUpdate();\r\n\r\n        " +
                    "protected override void OnAttachNativeEvents()\r\n        {\r\n            var thisA" +
                    "sIRx");
            
            #line 92 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" = (IRx");
            
            #line 92 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(")this;\r\n            ");
            
            #line 93 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("            if (thisAsIRx");
            
            #line 94 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 94 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("Action != null || thisAsIRx");
            
            #line 94 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 94 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs != null)\r\n            {\r\n                NativeControl.");
            
            #line 96 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write(" += NativeControl_");
            
            #line 96 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n            ");
            
            #line 98 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            base.OnAttachNativeEvents();\r\n        }\r\n\r\n        ");
            
            #line 103 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("        private void NativeControl_");
            
            #line 104 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("(object sender, ");
            
            #line 104 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.EventHandlerType.GetGenericArguments()[0].Name));
            
            #line default
            #line hidden
            this.Write(" e)\r\n        {\r\n            var thisAsIRx");
            
            #line 106 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" = (IRx");
            
            #line 106 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(")this;\r\n            thisAsIRx");
            
            #line 107 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 107 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("Action?.Invoke();\r\n            thisAsIRx");
            
            #line 108 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 108 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs?.Invoke(e);\r\n        }\r\n        ");
            
            #line 110 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        protected override void OnDetachNativeEvents()\r\n        {\r\n            " +
                    "if (NativeControl != null)\r\n            {\r\n            ");
            
            #line 116 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("            NativeControl.");
            
            #line 117 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write(" -= NativeControl_");
            
            #line 117 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n            ");
            
            #line 118 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n\r\n            base.OnDetachNativeEvents();\r\n        }\r\n\r\n    }\r\n  " +
                    "  ");
            
            #line 125 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (IsTypeNotAbstractWithEmptyConstructur) { 
            
            #line default
            #line hidden
            this.Write("    public partial class Rx");
            
            #line 126 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" : Rx");
            
            #line 126 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 126 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public Rx");
            
            #line 128 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("()\r\n        { \r\n        \r\n        }\r\n\r\n        public Rx");
            
            #line 133 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("(Action<");
            
            #line 133 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("> componentRefAction)\r\n            : base(componentRefAction)\r\n        {\r\n\r\n     " +
                    "   }\r\n    }\r\n    ");
            
            #line 139 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    public static partial class Rx");
            
            #line 140 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("Extensions\r\n    {\r\n        ");
            
            #line 142 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var property in Properties) { 
            
            #line default
            #line hidden
            this.Write("        public static T ");
            
            #line 143 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 143 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 143 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 143 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.CamelCase()));
            
            #line default
            #line hidden
            this.Write(") where T : IRx");
            
            #line 143 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 145 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 145 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 145 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 145 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.CamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            return ");
            
            #line 146 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        ");
            
            #line 148 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (property.PropertyType.Name == "Thickness") { 
            
            #line default
            #line hidden
            this.Write("        public static T ");
            
            #line 149 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 149 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", double leftRight, double topBottom) where T : IRx");
            
            #line 149 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 151 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 151 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 151 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(new Thickness(leftRight, topBottom));\r\n            return ");
            
            #line 152 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        public static T ");
            
            #line 154 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 154 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", double uniformSize) where T : IRx");
            
            #line 154 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 156 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 156 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 156 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(new Thickness(uniformSize));\r\n            return ");
            
            #line 157 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        ");
            
            #line 159 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 160 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (property.PropertyType.Name == "ImageSource") { 
               var propertyName = property.Name.Length <= 6 ? property.Name : property.Name.Substring(0, property.Name.Length - 6); 
            
            #line default
            #line hidden
            this.Write("\r\n        public static T ");
            
            #line 163 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 163 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", string file) where T : IRx");
            
            #line 163 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 165 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 165 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 165 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(ImageSource.FromFile(file));\r\n            return ");
            
            #line 166 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        public static T ");
            
            #line 168 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 168 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", string resourceName, Assembly sourceAssembly) where T : IRx");
            
            #line 168 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 170 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 170 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 170 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(ImageSource.FromResource(resourceName, sourceAssembly));\r\n            return ");
            
            #line 171 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        public static T ");
            
            #line 173 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 173 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Uri imageUri) where T : IRx");
            
            #line 173 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 175 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 175 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 175 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(ImageSource.FromUri(imageUri));\r\n            return ");
            
            #line 176 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        public static T ");
            
            #line 178 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 178 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Uri imageUri, bool cachingEnabled, TimeSpan cacheValidity) where T : IRx");
            
            #line 178 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 180 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 180 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 180 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(new UriImageSource\r\n            {\r\n                Uri = imageUri,\r\n           " +
                    "     CachingEnabled = cachingEnabled,\r\n                CacheValidity = cacheVali" +
                    "dity\r\n            });\r\n            return ");
            
            #line 186 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        public static T ");
            
            #line 188 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 188 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Func<Stream> imageStream) where T : IRx");
            
            #line 188 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 190 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 190 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 190 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.Name.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(ImageSource.FromStream(imageStream));\r\n            return ");
            
            #line 191 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n            ");
            
            #line 193 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 194 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 195 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("        public static T On");
            
            #line 196 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 196 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Action ");
            
            #line 196 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write("Action) where T : IRx");
            
            #line 196 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 198 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 198 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("Action = ");
            
            #line 198 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write("Action;\r\n            return ");
            
            #line 199 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n\r\n        public static T On");
            
            #line 202 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 202 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Action<");
            
            #line 202 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.EventHandlerType.GetGenericArguments()[0].Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 202 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs) where T : IRx");
            
            #line 202 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 204 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 204 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs = ");
            
            #line 204 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs;\r\n            return ");
            
            #line 205 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        ");
            
            #line 207 "C:\Source\github\reactorui-avalonia\src\AvaloniaReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class TypeSourceGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
